name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build-docker-image:
    #runs-on: [self-hosted, Windows, x64, DEVDEPLOYMENT]
    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      #run: docker build . --file Dockerfile --tag ace-safe-settings-image
           
    - name: Build Docker Image Locally
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: ace-safe-settings-image        
    - name: Inspect the Docker Image
      shell: bash
      run: |
        docker image inspect ace-safe-settings-image         
    - name: Run Functional Tests
      id: functionaltest
      shell: bash
      run: |
          docker run --env APP_ID=${{ vars.APP_ID }} --env PRIVATE_KEY=${{ vars.PRIVATE_KEY }} --env WEBHOOK_SECRET=${{ vars.WEBHOOK_SECRET }} -d -p 3000:3000 ace-safe-settings-image
          sleep 10
          #curl http://localhost:80
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: safesettingsregistry.azurecr.io
        username: safe-settings-registry
        password: lfuJXF6MYGELS1V8RVVRtEWvYIvq21XDaywfPY0znI+ACRCMzWvY
    #- name: Login into ACR
      #run: docker login -u safe-settings-registry -p lfuJXF6MYGELS1V8RVVRtEWvYIvq21XDaywfPY0znI+ACRCMzWvY safesettingsregistry.azurecr.io      
    - name: Push Docker Image
      if: ${{ success() }}
      uses: docker/build-push-action@v2
      with:
        #context: .
        #file: ./Dockerfile
        push: true
        tags: safesettingsregistry       
