name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    #runs-on: [self-hosted, Windows, x64, DEVDEPLOYMENT]
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, Windows, x64, DEV]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker build . --file Dockerfile --tag ace-safe-settings
      
    - name: Push the image into local
      run: docker save -o c:/temp/ace-safe-settings.tar centos:16
