name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build-docker-image:
    #runs-on: [self-hosted, Windows, x64, DEVDEPLOYMENT]
    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v3        
    
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      #run: docker build . --file Dockerfile --tag ace-safe-settings-image
           
    - name: Build Docker Image Locally
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: ace-safe-settings-image        
    - name: Inspect the Docker Image
      shell: bash
      run: |
        docker image inspect ace-safe-settings-image         
    - name: Run Functional Tests
      id: functionaltest
      shell: bash
      run: |
          docker run --env APP_ID=${{ vars.APP_ID }} --env PRIVATE_KEY=${{ vars.PRIVATE_KEY }} --env WEBHOOK_SECRET=${{ vars.WEBHOOK_SECRET }} -d -p 3000:3000 ace-safe-settings-image
          sleep 10
          #curl http://localhost:80
    - name: Login into ACR
      run: docker login -u safe-settings-registry -p lfuJXF6MYGELS1V8RVVRtEWvYIvq21XDaywfPY0znI+ACRCMzWvY safesettingsregistry.azurecr.io      
    - name: Push Docker Image
      if: ${{ success() }}
      uses: docker/build-push-action@v2
      with:
        #context: .
        #file: ./Dockerfile
        push: true
        tags: safesettingsregistry       
